apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: swin-tiny-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: swin-tiny-deployment
  minReplicaCount: 1
  maxReplicaCount: 100
  pollingInterval: 15  # Check every 15 seconds
  cooldownPeriod: 120  # Wait 2 minutes before scaling down
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 120  # Wait 1 minute before scaling up again
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          selectPolicy: Max
        scaleDown:
          stabilizationWindowSeconds: 120  # Wait 1 minute before scaling down (reduced from default)
          policies:
          - type: Percent
            value: 50
            periodSeconds: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090
      metricName: avg_request_duration_seconds
      query: |
        avg(
          rate(http_request_duration_seconds_sum[2m])
          /
          clamp_min(rate(http_request_duration_seconds_count[2m]), 1)
        )
      threshold: "0.020"  
    metricType: Value
