apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config-all
data:
# Configure GPU time-slicing to allow 16 pods to share a single GPU
  any: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 16 