apiVersion: v1
kind: Service
metadata:
  name: swin-tiny-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: swin-tiny-app
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer